import React, { useEffect } from 'react';

interface PayoutExplanationModalProps {
  onClose: () => void;
}

const InfoCard: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
    <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
        <h3 className="text-xl font-bold text-white mb-2">{title}</h3>
        <div className="text-gray-300 space-y-2">{children}</div>
    </div>
);

const PayoutExplanationModal: React.FC<PayoutExplanationModalProps> = ({ onClose }) => {
  useEffect(() => {
    const handleEsc = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleEsc);
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', handleEsc);
      document.body.style.overflow = 'unset';
    };
  }, [onClose]);

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div className="bg-gray-900 rounded-lg shadow-xl w-full max-w-2xl border border-purple-800" onClick={e => e.stopPropagation()}>
        <div className="p-8">
          <div className="flex justify-between items-start mb-6">
            <h2 className="text-3xl font-bold text-white">How You Earn on Crate TV</h2>
            <button onClick={onClose} className="text-gray-400 hover:text-white">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
          </div>
          
          <p className="text-gray-400 mb-8">We believe in transparency. Here’s a simple breakdown of how you earn money from your films on our platform.</p>

          <div className="space-y-6">
            <InfoCard title="1. Direct Support (Donations)">
              <p>When a viewer loves your film, they can send a direct donation to support your work.</p>
              <p>You receive <strong className="text-green-400">70%</strong> of every donation. Crate TV's 30% share covers payment processing fees and helps us maintain and grow the platform.</p>
              <p className="text-sm text-gray-500 italic">Example: On a $5.00 donation, you get $3.50.</p>
            </InfoCard>

            <InfoCard title="2. Ad Revenue (From Views)">
              <p>Your film automatically earns money from the ads shown before it plays. We use an industry-standard model called CPM (Cost Per Thousand Views).</p>
              <p>Our rate is <strong className="text-blue-400">$5.00 CPM</strong>, and you receive <strong className="text-blue-400">50%</strong> of all ad revenue generated by your film.</p>
              <p className="text-sm text-gray-500 italic">Example: If your film gets 10,000 views, it generates $50.00 in ad revenue, and your share is $25.00.</p>
            </InfoCard>
          </div>

          <div className="mt-8 text-center">
            <button onClick={onClose} className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-6 rounded-md">
                Got It
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PayoutExplanationModal;